### ISSUE TITLE
Crash when album name ends with a dot '.'

### ISSUE THREAD

**Issue by kacciocciacciara** [Otiel/BandcampDownloader#102]
Downloading the following album results in a hard crash of the application after the first song download try. My guess is that it's the album title, starting with 3 dots. Here are the application and system logs.
Thank you for your work and passion :)

Application log:
----- BEGIN -----
2019-06-11 10:35:20.4550  INFO   Starting download...
2019-06-11 10:35:20.5358  INFO   Retrieving album data for https://empyrium.bandcamp.com/album/der-wie-ein-blitz-vom-himmel-fiel
2019-06-11 10:35:22.2386  INFO   Computing size for album "...Der Wie Ein Blitz Vom Himmel Fiel..."...
2019-06-11 10:35:22.4274  DEBUG  Retrieved the size of the cover art file for album "...Der Wie Ein Blitz Vom Himmel Fiel..."
2019-06-11 10:35:22.6577  DEBUG  Retrieved the size of the MP3 file for the track "Midnight, Moonlight And A Dark Romance"
2019-06-11 10:35:22.6577  DEBUG  Retrieved the size of the MP3 file for the track "My Nocturnal Queen"
2019-06-11 10:35:22.6860  DEBUG  Retrieved the size of the MP3 file for the track "Outroduction"
2019-06-11 10:35:22.7083  DEBUG  Retrieved the size of the MP3 file for the track "Introduction: Astrum Luciferi"
2019-06-11 10:35:23.1054  INFO   Downloaded artwork for album "...Der Wie Ein Blitz Vom Himmel Fiel..."
2019-06-11 10:35:23.1314  DEBUG  Downloading track "Introduction: Astrum Luciferi" from url: https://t4.bcbits.com/stream/3ba46ebbfcd225f322ba5af138c4e8b8/mp3-128/4223981772?p=0&ts=1560328465&t=2aa6ea47604e43a6fa432c1ff8f53b2291a52e84&token=1560328465_e6f807ccd9a0f9c30f4e5cfcbf67205780e90c9f
2019-06-11 10:35:23.1393  DEBUG  Downloading track "Midnight, Moonlight And A Dark Romance" from url: https://t4.bcbits.com/stream/322a218f2e8481d06b5accf483a30f50/mp3-128/498419889?p=0&ts=1560328465&t=3b511f96bb87c3d18f6860f6a6f009fea2a3c424&token=1560328465_9f0d3407d0c3597008f0ed4967ea0bf212ec137c
2019-06-11 10:35:23.1393  DEBUG  Downloading track "My Nocturnal Queen" from url: https://t4.bcbits.com/stream/439ff5a3f4cb3898df33e1e612738028/mp3-128/4256817905?p=0&ts=1560328465&t=30e44d78c0d8c55415dbe0a1dc62d7d02cf1facb&token=1560328465_e25b052918aec43317149fb232ad8f111f46d4d9
2019-06-11 10:35:23.1513  DEBUG  Downloading track "Outroduction" from url: https://t4.bcbits.com/stream/0bd7118a868b7edfb0c49be64b30ef03/mp3-128/1282567990?p=0&ts=1560328465&t=6f957f3d6945e99a8053d59dfc36a244e469fed5&token=1560328465_507187029de99c51aedc6bebee7097f4e17fbec6
2019-06-11 10:35:23.1513  WARN   Unable to download track "01 - Introduction_ Astrum Luciferi.mp3" from album "...Der Wie Ein Blitz Vom Himmel Fiel...". Try 1 of 7
2019-06-11 10:35:23.1713  WARN   Unable to download track "02 - Midnight, Moonlight And A Dark Romance.mp3" from album "...Der Wie Ein Blitz Vom Himmel Fiel...". Try 1 of 7
2019-06-11 10:35:23.1713  WARN   Unable to download track "03 - My Nocturnal Queen.mp3" from album "...Der Wie Ein Blitz Vom Himmel Fiel...". Try 1 of 7
2019-06-11 10:35:23.1832  WARN   Unable to download track "04 - Outroduction.mp3" from album "...Der Wie Ein Blitz Vom Himmel Fiel...". Try 1 of 7
----- END -----

System log:
----- BEGIN -----
Application: BandcampDownloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess)
   at System.Net.WebClient.DownloadFileAsync(System.Uri, System.String, System.Object)

Exception Info: System.Net.WebException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<DownloadAndTagTrackAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<>c__DisplayClass13_0+<<DownloadAlbumAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<DownloadAlbumAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.DownloadManager+<StartDownloadsAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.WindowMain+<StartDownloadAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at BandcampDownloader.WindowMain+<ButtonStart_Click>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at BandcampDownloader.App.Main()
----- END -----

**Comment by Otiel** [comment]
Thanks for reporting this and for the kind words. ❤️ 

You are almost right: the issue indeed comes from the title name and the dots, but it's the trailing dots that cause the crash, not the three starting ones.

[Rules](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file) are:
>Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not.

BandcampDownloader currently tries to create the album folder with the name `...Der Wie Ein Blitz Vom Himmel Fiel...` while the last three dots are not authorized.

This will be fixed in the next version.

**Comment by kacciocciacciara** [comment]
Nice :)
Well, my guess was because . and .. are aliases for current and parent directory, I never thought trailing dots were a problem.
As a fellow developer, you never stop learning :)
Thank you

**Comment by Otiel** [comment]
This should be fixed in [1.0.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.0.0)

**Comment by kacciocciacciara** [comment]
Just updated, I confirm that the bug is fixed. Thanks!
