### ISSUE TITLE
The app doesn't launch, saying an unhandled error has occured.

### ISSUE THREAD

**Issue by SaveLeon** [Otiel/BandcampDownloader#137]
Whenever I try and launch the app, it just sends an error screen and sends me to the logs that say
2020-04-19 15:49:54.1273  FATAL  .NET Framework version: 4.8 or later
2020-04-19 15:49:54.2680  FATAL  System.Windows.Markup.XamlParseException Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
2020-04-19 15:49:54.2992  FATAL     at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BandcampDownloader.App.Main()
2020-04-19 15:49:54.2992  FATAL  System.Runtime.InteropServices.COMException UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
2020-04-19 15:49:54.3148  FATAL     at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.CreateChannels()
   at System.Windows.Media.MediaSystem.ConnectChannels(MediaContext mc)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)

**Comment by Otiel** [comment]
* Are you running the app on a virtual machine?
* What's your Windows version?

**Comment by SaveLeon** [comment]
This isn't a VM, the Windows 10 version is 1909 (build 18363.778)

**Comment by SaveLeon** [comment]
I think I might understand, what caused the issue. Just checked the dev branch, and app.config said the NET Framework version should be 4.7.2 or whatever, while I'm running 4.8. CAN it be an issue or i'm just dumb? I'm not expirienced in coding, having only basic "Hello World programm" knowledge.

**Comment by SaveLeon** [comment]
> 
> 
> I think I might understand, what caused the issue. Just checked the dev branch, and app.config said the NET Framework version should be 4.7.2 or whatever, while I'm running 4.8. CAN it be an issue or i'm just dumb? I'm not expirienced in coding, having only basic "Hello World programm" knowledge.
 
YES, I can confirm, it is caused by the NET. Framework version! I think it just doesn't support 4.8, that is the issue.

**Comment by Otiel** [comment]
That's weird, it should work even if you do not have .NET Framework v4.7.2 installed on your machine, as it is [backward-compatible](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility#backward-compatibility-and-the-net-framework).

>YES, I can confirm, it is caused by the NET. Framework version!

Did you install .NET Framework v4.7.2?

**Comment by SaveLeon** [comment]
I tried it on a different PC w/ the same version of Windows, but running .NET Framework v4.7.2 and it worked, but on my main PC it refuses to work, complaining about smth

**Comment by Otiel** [comment]
Can you try running the attached version on your main PC (the one with .NET Framework v4.8) and let me know what happens?

[BandcampDownloader-withoutSku.zip](https://github.com/Otiel/BandcampDownloader/files/4521464/BandcampDownloader-withoutSku.zip)

**Comment by SaveLeon** [comment]
Now it shows me a different error :

2020-04-23 16:39:46.3180  FATAL  .NET Framework version: 4.8 or later
2020-04-23 16:39:46.4118  FATAL  System.IO.FileLoadException Не удалось загрузить файл или сборку "WPFLocalizeExtension, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Ошибка во время управляемого ввода-вывода. (Исключение из HRESULT: 0x80131620)
2020-04-23 16:39:46.4430  FATAL     в BandcampDownloader.LanguageHelper.ApplyLanguage(Language language)
   в BandcampDownloader.App.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в BandcampDownloader.App.Main()
2020-04-23 16:39:46.4587  FATAL  System.IO.Compression.ZLibException Несовместимое состояние потока базовой процедуры сжатия.
2020-04-23 16:39:46.4743  FATAL     в System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
   в System.IO.Compression.InflaterZlib.ReadInflateOutput(Byte[] outputBuffer, Int32 offset, Int32 length, FlushCode flushCode, Int32& bytesRead)
   в System.IO.Compression.InflaterZlib.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   в System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   в Costura.AssemblyLoader.CopyTo(Stream source, Stream destination)
   в Costura.AssemblyLoader.LoadStream(String fullName)
   в Costura.AssemblyLoader.ReadFromEmbeddedResources(Dictionary`2 assemblyNames, Dictionary`2 symbolNames, AssemblyName requestedAssemblyName)
   в Costura.AssemblyLoader.ResolveAssembly(Object sender, ResolveEventArgs e)
   в System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
2020-04-25 21:05:43.2199  FATAL  .NET Framework version: 4.8 or later
2020-04-25 21:05:46.4224  FATAL  System.Windows.Markup.XamlParseException Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
2020-04-25 21:05:47.0944  FATAL     at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BandcampDownloader.App.Main()
2020-04-25 21:05:47.2379  FATAL  System.Runtime.InteropServices.COMException UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
2020-04-25 21:05:48.3084  FATAL     at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.CreateChannels()
   at System.Windows.Media.MediaSystem.ConnectChannels(MediaContext mc)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
2020-04-25 21:06:01.4203  FATAL  .NET Framework version: 4.8 or later
2020-04-25 21:06:01.5765  FATAL  System.Windows.Markup.XamlParseException Add value to collection of type 'System.Windows.Controls.UIElementCollection' threw an exception.
2020-04-25 21:06:01.6078  FATAL     at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BandcampDownloader.App.Main()
2020-04-25 21:06:01.6234  FATAL  System.Runtime.InteropServices.COMException UCEERR_RENDERTHREADFAILURE (Exception from HRESULT: 0x88980406)
2020-04-25 21:06:01.6390  FATAL     at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Media.MediaContext.CreateChannels()
   at System.Windows.Media.MediaSystem.ConnectChannels(MediaContext mc)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Media.Visual.VerifyAPIReadWrite()
   at System.Windows.Media.VisualCollection.Add(Visual visual)
   at System.Windows.Controls.UIElementCollection.AddInternal(UIElement element)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.Add(Object collection, XamlType collectionType, Object value, XamlType valueXamlType)
2020-04-25 21:06:01.8266  FATAL  .NET Framework version: 4.8 or later
2020-04-25 21:06:02.0766  FATAL  System.IO.FileLoadException Не удалось загрузить файл или сборку "WPFLocalizeExtension, Version=3.3.1.0, Culture=neutral, PublicKeyToken=null" либо одну из их зависимостей. Ошибка во время управляемого ввода-вывода. (Исключение из HRESULT: 0x80131620)
2020-04-25 21:06:02.1079  FATAL     в BandcampDownloader.LanguageHelper.ApplyLanguage(Language language)
   в BandcampDownloader.App.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в BandcampDownloader.App.Main()
2020-04-25 21:06:02.1235  FATAL  System.IO.Compression.ZLibException Несовместимое состояние потока базовой процедуры сжатия.
2020-04-25 21:06:02.1391  FATAL     в System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
   в System.IO.Compression.InflaterZlib.ReadInflateOutput(Byte[] outputBuffer, Int32 offset, Int32 length, FlushCode flushCode, Int32& bytesRead)
   в System.IO.Compression.InflaterZlib.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   в System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   в Costura.AssemblyLoader.CopyTo(Stream source, Stream destination)
   в Costura.AssemblyLoader.LoadStream(String fullName)
   в Costura.AssemblyLoader.ReadFromEmbeddedResources(Dictionary`2 assemblyNames, Dictionary`2 symbolNames, AssemblyName requestedAssemblyName)
   в Costura.AssemblyLoader.ResolveAssembly(Object sender, ResolveEventArgs e)
   в System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

I didn't do anything w/ the pc, everything is the same as it was

**Comment by SaveLeon** [comment]
GOD, I am braindead! I accidentally installed Win10 for ONE LANGUAGE when I was reinstalling the OS, that may be what caused the issue! Sorry for wasting your time!

**Comment by Otiel** [comment]
>I accidentally installed Win10 for ONE LANGUAGE when I was reinstalling the OS, that may be what caused the issue!

No it shouldn't be.

If you try to install .NET Framework v4.7.2 on your computer (can be downloaded [here](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net472-offline-installer)), I'm guessing it says that it is already installed, right?

**Comment by SaveLeon** [comment]
It says that a newer version of .NET Framework is installed, yes.

**Comment by SaveLeon** [comment]
I found out that the issue lies in a broken .NET Framework installation when I was reinstalling Windows. I'm gonna reinstall it again on the weekends and see, what will happen.

**Comment by Otiel** [comment]
Any luck after reinstalling your .NET Framework?

**Comment by Otiel** [comment]
Closing this issue as no more news. Feel free to reopen if this isn't solved.
