### ISSUE TITLE
Bandcamp downloader crashes on start

### ISSUE THREAD

**Issue by Efreak** [Otiel/BandcampDownloader#159]
I'm getting a crash when I start BandcampDownloader. I saw another issue mentioning windows event viewer; without this, I never would have thought to look there for an *application* crash log; another issue asked for an ini file, but I have no such file (that I know of); there's a json file here, but I think that's for an older version... Error text below:

<details>
<summary>Application Error</summary>

```
Faulting application name: BandcampDownloader.exe, version: 1.3.1.0, time stamp: 0x5dbd9974
Faulting module name: KERNELBASE.dll, version: 10.0.19041.488, time stamp: 0x5b4a3325
Exception code: 0xe0434352
Fault offset: 0x0000000000023e49
Faulting process id: 0x2634
Faulting application start time: 0x01d69a0da0fdfe0b
Faulting application path: C:\Programs\BandcampDownloader.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b5686c4e-e829-458b-8159-f3a00a293502
Faulting package full name: 
Faulting package-relative application ID: 
```

</details>
<details>
<summary>.NET Runtime</summary>

```
Application: BandcampDownloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
   at BandcampDownloader.App.InitializeLogger()
   at BandcampDownloader.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at BandcampDownloader.App.Main()
```
</details>

**Comment by Otiel** [comment]
Is .NET Framework v4.7.2 or later installed on your machine?

**Comment by Efreak** [comment]
output from [`dotnetversions`](https://github.com/jmalarcon/DotNetVersions/)` && ver`:
```
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084

Microsoft Windows [Version 10.0.19041.508]
```

If 4.7.x counts, then yes; if not, then no (.NET is weird about version numbers, so I'm not actually sure here)

**Comment by Otiel** [comment]
It should be good with what you have installed.

Is there a _BandcampDownloader.log_ file created next to the _BandcampDownloader.exe_?
Do you still have the issue with [v1.3.3](https://github.com/Otiel/BandcampDownloader/releases/tag/v1.3.3)?

**Comment by Efreak** [comment]
I'm on the latest version, so yes. I just replaced it. No, there's no log file here.

**Comment by Otiel** [comment]
There's a _BandcampDownloader.log_ file created in another folder than _BandcampDownloader.exe_?

Where are you running _BandcampDownloader.exe_ from?

**Comment by Efreak** [comment]
It's being run from c:\Programs, an all-users-rw folder I have for portable single-binary/small folder software and python, etc applications that I run from source; permission-wise, it's effectively the same as my downloads folder, but less messy.

(Apologies for delay, I keep messing to get the location/contents of other log file, but life keeps happening and I've been trying to stay out of the browser in my little free time)

**Comment by Otiel** [comment]
Hmm if there are other programs located in the same folder, it might be a conflict between a _dll_ included in BandcampDownloader.exe and another one in the folder. Can you try moving _BandcampDownloader.exe_ to its own folder?

(No worries for the delay, I'm myself not flawless these days to provide support here)

**Comment by Efreak** [comment]
V1.3.3 has launched successfully with that (I'm on mobile/remote access, so I haven't tested anything else yet). It's odd, though--I have several other single-binary .net applications that run just fine from here. I'm have to see if I can figure out what's messing up...

**Comment by Otiel** [comment]
Do you have any _NLog.dll_ or similarly named file in your `C:\Programs` folder?

**Comment by Otiel** [comment]
Closing this since it seems to be resolved. Do not hesitate to reopen if needed.
