### ISSUE TITLE
Some characters force an exception in the app

### ISSUE THREAD

**Issue by teeto** [Otiel/BandcampDownloader#189]
The app cant download this url:
https://grossorecords.bandcamp.com/album/roots-of-salsa-vol-2

**Comment by Otiel** [comment]
Thanks for the report!

Attaching trace:
```
2021-08-04 17:10:56.8646  INFO   Starting download...
2021-08-04 17:10:56.9247  INFO   Retrieving album data for https://grossorecords.bandcamp.com/album/roots-of-salsa-vol-2
2021-08-04 17:10:59.2097  INFO   Computing size for album "Roots of Salsa. Vol. 2"...
2021-08-04 17:11:01.0043  DEBUG  Retrieved the size of the cover art file for album "Roots of Salsa. Vol. 2"
2021-08-04 17:11:02.2265  DEBUG  Retrieved the size of the MP3 file for the track "Jos� Curbelo and His Orchestra (1953) - La familia"
2021-08-04 17:11:02.2583  DEBUG  Retrieved the size of the MP3 file for the track "Pacho Alonso con Bebo Vald�s y Su Orquesta (1960) - Yo no quiero piedra en mi camino"
2021-08-04 17:11:02.3709  DEBUG  Retrieved the size of the MP3 file for the track "Estrellas de Chocolate (1960) - Fania"
2021-08-04 17:11:02.4240  DEBUG  Retrieved the size of the MP3 file for the track "La Sonora Matancera (1954) - Suj�tate la lengua"
2021-08-04 17:11:02.4827  DEBUG  Retrieved the size of the MP3 file for the track "Conjunto Ni�gara (1945) - Tumba mab�"
2021-08-04 17:11:02.5399  DEBUG  Retrieved the size of the MP3 file for the track "Conjunto Colonial de Nelo Sosa (1950) - El paso del mulo"
2021-08-04 17:11:02.6422  DEBUG  Retrieved the size of the MP3 file for the track "Chappot�n y Sus Estrellas (1958) - Micaela me bot�"
2021-08-04 17:11:02.7057  DEBUG  Retrieved the size of the MP3 file for the track "Flores Vald�z y Su Conjunto Musical (195?)  - Salsa"
2021-08-04 17:11:02.8378  DEBUG  Retrieved the size of the MP3 file for the track "Conjunto Kuvabana de Alberto Ru�z (1947) - Corta el bonche"
2021-08-04 17:11:02.8956  DEBUG  Retrieved the size of the MP3 file for the track "Tr�o Matamoros (1960)  - Nadie se salva de la rumba"
2021-08-04 17:11:02.9421  DEBUG  Retrieved the size of the MP3 file for the track "La Orquesta Siboney de Pepito Torres (1944) - Llora timbero"
2021-08-04 17:11:03.1157  DEBUG  Retrieved the size of the MP3 file for the track "Tito Rodr�guez y Los Lobos Del Mambo (1951) - Hay cr�neo"
2021-08-04 17:11:19.8916  INFO   Downloaded artwork for album "Roots of Salsa. Vol. 2"
2021-08-04 17:11:19.9046  DEBUG  Downloading track "La Sonora Matancera (1954) - Suj�tate la lengua" from url: https://t4.bcbits.com/stream/c0349dd92dabb6ba10596b4278c652b4/mp3-128/2997697813?p=0&ts=1628176257&t=09f34e37c8d6f55db4e8ad9bbee4d83e10fe3989&token=1628176257_c4c6315111a65c6d6388c0b6596448cf292b8d17
2021-08-04 17:11:19.9132  DEBUG  Downloading track "Conjunto Colonial de Nelo Sosa (1950) - El paso del mulo" from url: https://t4.bcbits.com/stream/e541f7021786e419cbae7a74719875c2/mp3-128/554931411?p=0&ts=1628176257&t=d84859c8b6d28a0712a7bb65d3bbf97bef2884f8&token=1628176257_4c0a4f7e6e439e6c2c2ed38a34a44859fd000026
2021-08-04 17:11:19.9132  DEBUG  Downloading track "Chappot�n y Sus Estrellas (1958) - Micaela me bot�" from url: https://t4.bcbits.com/stream/e7d7e780535eae9d584e8b35d4c006bb/mp3-128/2976945303?p=0&ts=1628176257&t=bc293cb785fe78c253fed0f002a165a7a593ab78&token=1628176257_aa0f72d96362b74fa33ab39f699db417a64186d6
2021-08-04 17:11:19.9132  DEBUG  Downloading track "Tr�o Matamoros (1960)  - Nadie se salva de la rumba" from url: https://t4.bcbits.com/stream/75f187fabf30bd124e3ea7e86fa06dce/mp3-128/1654462822?p=0&ts=1628176257&t=daf5f29423e24606aa122efb7851d0de4b4b2577&token=1628176257_aae6d121fc09ba114d7ab231b4cf6024decd3ae7
2021-08-04 17:11:19.9302  DEBUG  Downloading track "Jos� Curbelo and His Orchestra (1953) - La familia" from url: https://t4.bcbits.com/stream/9cd3eb6125339f6ab3213043d2a2b7e6/mp3-128/3929078848?p=0&ts=1628176257&t=516167fc031643324a568d6bc38c001db72e4bef&token=1628176257_2e1a055b85416abfda4964c0a083f1166a094316
2021-08-04 17:11:19.9302  DEBUG  Downloading track "Flores Vald�z y Su Conjunto Musical (195?)  - Salsa" from url: https://t4.bcbits.com/stream/6ad3173ea13d1730105618eb2dbe0397/mp3-128/1493032422?p=0&ts=1628176257&t=0a11cd9f80b9b733feca4e4574ac72d975677734&token=1628176257_6cdcb58727c1d08a68c1df2dd60262b802ff4eb1
2021-08-04 17:11:19.9302  DEBUG  Downloading track "Tito Rodr�guez y Los Lobos Del Mambo (1951) - Hay cr�neo" from url: https://t4.bcbits.com/stream/ebadbd30e3d8f7ca9d1e957c297a5692/mp3-128/3159854613?p=0&ts=1628176257&t=5ad10779543dbd8ab1dd5d44dd97ea02147d625c&token=1628176257_2929d7313a30f7d5853de8ebff1e902cd9f7b4f6
2021-08-04 17:11:19.9462  DEBUG  Downloading track "Estrellas de Chocolate (1960) - Fania" from url: https://t4.bcbits.com/stream/eb578fc15a77348f70e2f10856297bf8/mp3-128/1922629521?p=0&ts=1628176257&t=a6e41d4c0bd585ef695ac642f6632dce4f2adcbf&token=1628176257_90980e5abab40808d6bee29cdf19ba569e8c9116
2021-08-04 17:11:19.9462  DEBUG  Downloading track "Pacho Alonso con Bebo Vald�s y Su Orquesta (1960) - Yo no quiero piedra en mi camino" from url: https://t4.bcbits.com/stream/23eaa90519de3c746da3d02187ad4e3c/mp3-128/2218642585?p=0&ts=1628176257&t=1c9b6ce8a0bdfd626343d1358c5e749e881fcab7&token=1628176257_f389bdce48541d3ee38a0ac4edcee92cf202ba36
2021-08-04 17:11:19.9462  DEBUG  Downloading track "Conjunto Kuvabana de Alberto Ru�z (1947) - Corta el bonche" from url: https://t4.bcbits.com/stream/c9bdf3017529577946faa6e615809a68/mp3-128/596393925?p=0&ts=1628176257&t=f3c211c82f981c7d821aeb3e6854942eeb6bf03d&token=1628176257_380796466854a6547357fcf3c7370b4f28376b80
2021-08-04 17:11:19.9601  DEBUG  Downloading track "Conjunto Ni�gara (1945) - Tumba mab�" from url: https://t4.bcbits.com/stream/a0301ba9839d680476a15a8da3c73aed/mp3-128/2124128511?p=0&ts=1628176257&t=aca5103a7fb89c3a5fb142ae12dfa5f75ee17612&token=1628176257_e2a36adb3ab61fd38b305470b650a5a01f738925
2021-08-04 17:11:19.9601  DEBUG  Downloading track "La Orquesta Siboney de Pepito Torres (1944) - Llora timbero" from url: https://t4.bcbits.com/stream/b1b0b9a77d55c84a39994b77c894a861/mp3-128/3363488081?p=0&ts=1628176257&t=f29337af1b3a2389edde6f5c85a03d68be0b5004&token=1628176257_a6fbbd777a1ca659bf6a570ebee31128ac926bf7
2021-08-04 17:11:19.9792  FATAL  .NET Framework version: 4.8 or later
2021-08-04 17:11:19.9792  FATAL  System.ArgumentException Illegal characters in path.
2021-08-04 17:11:19.9792  FATAL     at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at BandcampDownloader.DownloadManager.<DownloadAndTagTrackAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.DownloadManager.<>c__DisplayClass14_0.<<DownloadAlbumAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.DownloadManager.<DownloadAlbumAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.DownloadManager.<StartDownloadsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.WindowMain.<StartDownloadAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.WindowMain.<ButtonStart_Click>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BandcampDownloader.App.Main()

```
