### ISSUE TITLE
https://psychic-health.bandcamp.com/track

### ISSUE THREAD

**Issue by Exorcistof** [Otiel/BandcampDownloader#197]
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
ValueError: source code string cannot contain null bytes

[Program finished]

**Comment by Otiel** [comment]
Wrong project? There's no python in BandcampDownloader.
