### ISSUE TITLE
BandcampDownloader breaks with Japanese characters

### ISSUE THREAD

**Issue by dertuxmalwieder** [Otiel/BandcampDownloader#213]
I can reliably reproduce the following issue:

Downloading the [album *魔術師の城​/​The Sorcerer's Castle*](https://risatakeda.bandcamp.com/album/the-sorcerers-castle) works well, but after the files are downloaded, the application crashes, telling me I should report an unhandled error. As this does not happen with [another album](https://risatakeda.bandcamp.com/album/trois) by the same artist, I could imagine that the album title is the problem here.

The target file system is a QNAP NAS, but this has not been an issue with any other album yet:

`DownloadsPath=\\datengrab\musik_todo\{artist} - {album} [{year}]`

Relevant part of the (long) log file:

```
2022-04-12 20:17:15.4172  INFO   Starting download...
2022-04-12 20:17:15.4412  INFO   Retrieving album data for https://risatakeda.bandcamp.com/album/the-sorcerers-castle
2022-04-12 20:17:15.4602  DEBUG  Downloading album info from url: https://risatakeda.bandcamp.com/album/the-sorcerers-castle
2022-04-12 20:17:16.6412  INFO   Computing size for album "?????/The Sorcerer's Castle"...
2022-04-12 20:17:16.6812  DEBUG  Retrieved the size of the cover art file for album "?????/The Sorcerer's Castle"
2022-04-12 20:17:16.7192  DEBUG  Retrieved the size of the MP3 file for the track "The Emperor's Prophecy and the Knights-??????????"
2022-04-12 20:17:16.7692  DEBUG  Retrieved the size of the MP3 file for the track "Prologue-?????"
2022-04-12 20:17:16.7952  DEBUG  Retrieved the size of the MP3 file for the track "Torrential Rain in Wasteland-?????"
2022-04-12 20:17:16.8202  DEBUG  Retrieved the size of the MP3 file for the track "Decisive Battle?The Castle Collapses-??????-?????"
2022-04-12 20:17:16.8522  DEBUG  Retrieved the size of the MP3 file for the track "Dawn-???"
2022-04-12 20:17:16.9002  DEBUG  Retrieved the size of the MP3 file for the track "Resurrection of Demons-???????"
2022-04-12 20:17:16.9252  DEBUG  Retrieved the size of the MP3 file for the track "The Sorcerer's Spooky Altar- ??????????"
2022-04-12 20:17:16.9482  DEBUG  Retrieved the size of the MP3 file for the track "The Enchanted World-???????????"
2022-04-12 20:17:16.9722  DEBUG  Retrieved the size of the MP3 file for the track "Clash-?????????"
2022-04-12 20:17:16.9942  DEBUG  Retrieved the size of the MP3 file for the track "Epilogue-?????"
2022-04-12 20:17:17.0142  DEBUG  Retrieved the size of the MP3 file for the track "Appearance of the Castle-????"
2022-04-12 20:17:17.0492  DEBUG  Downloading artwork from url: https://f4.bcbits.com/img/a3925661065_0.jpg
2022-04-12 20:17:18.4012  INFO   Downloaded artwork for album "?????/The Sorcerer's Castle"
2022-04-12 20:17:18.4242  DEBUG  Downloading track "Prologue-?????" from url: https://t4.bcbits.com/stream/20ca3c2ee66799a013ee33f7e2c505e1/mp3-128/252844541?p=0&ts=1649873835&t=de5b42b185a57b2ae28482e9b8d09b5a29fb4559&token=1649873835_06dee29579d178415c3332a9bb1623b92d5adfcf
2022-04-12 20:17:18.4452  DEBUG  Downloading track "Prologue-?????" from url: https://t4.bcbits.com/stream/20ca3c2ee66799a013ee33f7e2c505e1/mp3-128/252844541?p=0&ts=1649873835&t=de5b42b185a57b2ae28482e9b8d09b5a29fb4559&token=1649873835_06dee29579d178415c3332a9bb1623b92d5adfcf
2022-04-12 20:17:18.4942  DEBUG  Downloading track "The Emperor's Prophecy and the Knights-??????????" from url: https://t4.bcbits.com/stream/4beb3630e6baef0719ce59b5701f285a/mp3-128/3579749073?p=0&ts=1649873835&t=febb48dad3e974433cfdc63bb26610eaae4f446f&token=1649873835_dc9d55e501b529386f71a3a0a2c983def38d957c
2022-04-12 20:17:18.5142  DEBUG  Downloading track "The Emperor's Prophecy and the Knights-??????????" from url: https://t4.bcbits.com/stream/4beb3630e6baef0719ce59b5701f285a/mp3-128/3579749073?p=0&ts=1649873835&t=febb48dad3e974433cfdc63bb26610eaae4f446f&token=1649873835_dc9d55e501b529386f71a3a0a2c983def38d957c
2022-04-12 20:17:18.5332  DEBUG  Downloading track "Torrential Rain in Wasteland-?????" from url: https://t4.bcbits.com/stream/3080c893a37258fcedd68600f08bb8a4/mp3-128/197080604?p=0&ts=1649873835&t=da3fa432e588baf71715ef3c10cce5483c100197&token=1649873835_98460db99ba84869e6a0a97305507ee8415fd9b6
2022-04-12 20:17:18.5542  DEBUG  Downloading track "Torrential Rain in Wasteland-?????" from url: https://t4.bcbits.com/stream/3080c893a37258fcedd68600f08bb8a4/mp3-128/197080604?p=0&ts=1649873835&t=da3fa432e588baf71715ef3c10cce5483c100197&token=1649873835_98460db99ba84869e6a0a97305507ee8415fd9b6
2022-04-12 20:17:18.5762  DEBUG  Downloading track "Appearance of the Castle-????" from url: https://t4.bcbits.com/stream/624e6ed2b5e950d43666e2a437def0eb/mp3-128/3473410766?p=0&ts=1649873835&t=fa51a4702fe37a73bb08c9cda1a8d6584134c7d6&token=1649873835_1fb8711ddf85e40acface3ecf33809ad75aee5d6
2022-04-12 20:17:18.6002  DEBUG  Downloading track "Appearance of the Castle-????" from url: https://t4.bcbits.com/stream/624e6ed2b5e950d43666e2a437def0eb/mp3-128/3473410766?p=0&ts=1649873835&t=fa51a4702fe37a73bb08c9cda1a8d6584134c7d6&token=1649873835_1fb8711ddf85e40acface3ecf33809ad75aee5d6
2022-04-12 20:17:18.6277  DEBUG  Downloading track "The Sorcerer's Spooky Altar- ??????????" from url: https://t4.bcbits.com/stream/966059db4c5e9e02eb366f96a1aad24d/mp3-128/2531226707?p=0&ts=1649873835&t=d51f33a05bbbc6a1e177393b45541fa1f41bc3cc&token=1649873835_f59dcc7b662e36615c0b079ccee81d7bd84406e1
2022-04-12 20:17:18.6467  DEBUG  Downloading track "The Sorcerer's Spooky Altar- ??????????" from url: https://t4.bcbits.com/stream/966059db4c5e9e02eb366f96a1aad24d/mp3-128/2531226707?p=0&ts=1649873835&t=d51f33a05bbbc6a1e177393b45541fa1f41bc3cc&token=1649873835_f59dcc7b662e36615c0b079ccee81d7bd84406e1
2022-04-12 20:17:18.6717  DEBUG  Downloading track "Resurrection of Demons-???????" from url: https://t4.bcbits.com/stream/7ca6b9fc0c36cd09f8c5fe79c708047a/mp3-128/3399568587?p=0&ts=1649873835&t=2d7dd2c5643ecaf993f46ce1dd466ad6bb6881b2&token=1649873835_54fc912234d54173d056bad257fc6d12b29cff02
2022-04-12 20:17:18.6927  DEBUG  Downloading track "Resurrection of Demons-???????" from url: https://t4.bcbits.com/stream/7ca6b9fc0c36cd09f8c5fe79c708047a/mp3-128/3399568587?p=0&ts=1649873835&t=2d7dd2c5643ecaf993f46ce1dd466ad6bb6881b2&token=1649873835_54fc912234d54173d056bad257fc6d12b29cff02
2022-04-12 20:17:18.7157  DEBUG  Downloading track "Clash-?????????" from url: https://t4.bcbits.com/stream/cdd9d59b6bc0ad87e6113dd400996d59/mp3-128/1782693478?p=0&ts=1649873835&t=c0ad4fbc80ce21cef835239c5e705938a8327ed4&token=1649873835_00db8626f2438d7763ea24095a4039469b07a0b5
2022-04-12 20:17:18.7412  DEBUG  Downloading track "Clash-?????????" from url: https://t4.bcbits.com/stream/cdd9d59b6bc0ad87e6113dd400996d59/mp3-128/1782693478?p=0&ts=1649873835&t=c0ad4fbc80ce21cef835239c5e705938a8327ed4&token=1649873835_00db8626f2438d7763ea24095a4039469b07a0b5
2022-04-12 20:17:18.7642  DEBUG  Downloading track "The Enchanted World-???????????" from url: https://t4.bcbits.com/stream/5feb463edb0970d200471ed0fe942438/mp3-128/3438236488?p=0&ts=1649873835&t=5c630e5d798e6913c9aa68141a7cb5df8115e1d5&token=1649873835_c61d7a585cd8c7af273fa2cfe12531ca11a743c0
2022-04-12 20:17:18.7922  DEBUG  Downloading track "The Enchanted World-???????????" from url: https://t4.bcbits.com/stream/5feb463edb0970d200471ed0fe942438/mp3-128/3438236488?p=0&ts=1649873835&t=5c630e5d798e6913c9aa68141a7cb5df8115e1d5&token=1649873835_c61d7a585cd8c7af273fa2cfe12531ca11a743c0
2022-04-12 20:17:18.8132  DEBUG  Downloading track "Decisive Battle?The Castle Collapses-??????-?????" from url: https://t4.bcbits.com/stream/bc0ca7c0d2f63333cfff6c69dc236e54/mp3-128/2787278508?p=0&ts=1649873835&t=d679c9f33e36acef428b4e1cd4e97d02e9d0e97f&token=1649873835_25a41bebce00ef4505ea15fb7457ce905d52e335
2022-04-12 20:17:18.8313  DEBUG  Downloading track "Decisive Battle?The Castle Collapses-??????-?????" from url: https://t4.bcbits.com/stream/bc0ca7c0d2f63333cfff6c69dc236e54/mp3-128/2787278508?p=0&ts=1649873835&t=d679c9f33e36acef428b4e1cd4e97d02e9d0e97f&token=1649873835_25a41bebce00ef4505ea15fb7457ce905d52e335
2022-04-12 20:17:18.8642  DEBUG  Downloading track "Dawn-???" from url: https://t4.bcbits.com/stream/c567150b61c4fcb180f2d778df93733d/mp3-128/436836518?p=0&ts=1649873835&t=9ee3ab7d25e7d7d80a8a0b784882d568a70432ba&token=1649873835_eb6b387df8d5f451b42ac03783c2ab8ff55cb497
2022-04-12 20:17:18.8873  DEBUG  Downloading track "Dawn-???" from url: https://t4.bcbits.com/stream/c567150b61c4fcb180f2d778df93733d/mp3-128/436836518?p=0&ts=1649873835&t=9ee3ab7d25e7d7d80a8a0b784882d568a70432ba&token=1649873835_eb6b387df8d5f451b42ac03783c2ab8ff55cb497
2022-04-12 20:17:18.9102  DEBUG  Downloading track "Epilogue-?????" from url: https://t4.bcbits.com/stream/6a932483fb6dccab3da7425036472747/mp3-128/2437098795?p=0&ts=1649873835&t=55c715421bb00e455ac15d5b1e6c56a4814ddcc3&token=1649873835_af8208fe04f07ab404c34993583774969ffff3a5
2022-04-12 20:17:18.9433  DEBUG  Downloading track "Epilogue-?????" from url: https://t4.bcbits.com/stream/6a932483fb6dccab3da7425036472747/mp3-128/2437098795?p=0&ts=1649873835&t=55c715421bb00e455ac15d5b1e6c56a4814ddcc3&token=1649873835_af8208fe04f07ab404c34993583774969ffff3a5
2022-04-12 20:17:19.5092  DEBUG  Downloaded track "Prologue-?????" from url: https://t4.bcbits.com/stream/20ca3c2ee66799a013ee33f7e2c505e1/mp3-128/252844541?p=0&ts=1649873835&t=de5b42b185a57b2ae28482e9b8d09b5a29fb4559&token=1649873835_06dee29579d178415c3332a9bb1623b92d5adfcf
2022-04-12 20:17:21.0063  DEBUG  Tags saved for track "01 Risa Takeda - Prologue-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:21.1902  DEBUG  Cover art saved in tags for track "01 Risa Takeda - Prologue-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:21.2072  INFO   Downloaded track "01 Risa Takeda - Prologue-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:21.3882  DEBUG  Downloaded track "Epilogue-?????" from url: https://t4.bcbits.com/stream/6a932483fb6dccab3da7425036472747/mp3-128/2437098795?p=0&ts=1649873835&t=55c715421bb00e455ac15d5b1e6c56a4814ddcc3&token=1649873835_af8208fe04f07ab404c34993583774969ffff3a5
2022-04-12 20:17:24.9872  DEBUG  Tags saved for track "11 Risa Takeda - Epilogue-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:25.2602  DEBUG  Cover art saved in tags for track "11 Risa Takeda - Epilogue-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:25.2752  INFO   Downloaded track "11 Risa Takeda - Epilogue-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:25.3622  DEBUG  Downloaded track "Appearance of the Castle-????" from url: https://t4.bcbits.com/stream/624e6ed2b5e950d43666e2a437def0eb/mp3-128/3473410766?p=0&ts=1649873835&t=fa51a4702fe37a73bb08c9cda1a8d6584134c7d6&token=1649873835_1fb8711ddf85e40acface3ecf33809ad75aee5d6
2022-04-12 20:17:27.5402  DEBUG  Tags saved for track "04 Risa Takeda - Appearance of the Castle-????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:27.9088  DEBUG  Cover art saved in tags for track "04 Risa Takeda - Appearance of the Castle-????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:27.9263  INFO   Downloaded track "04 Risa Takeda - Appearance of the Castle-????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:27.9413  DEBUG  Downloaded track "The Emperor's Prophecy and the Knights-??????????" from url: https://t4.bcbits.com/stream/4beb3630e6baef0719ce59b5701f285a/mp3-128/3579749073?p=0&ts=1649873835&t=febb48dad3e974433cfdc63bb26610eaae4f446f&token=1649873835_dc9d55e501b529386f71a3a0a2c983def38d957c
2022-04-12 20:17:31.9985  DEBUG  Tags saved for track "02 Risa Takeda - The Emperor's Prophecy and the Knights-??????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:32.4205  DEBUG  Cover art saved in tags for track "02 Risa Takeda - The Emperor's Prophecy and the Knights-??????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:32.4375  INFO   Downloaded track "02 Risa Takeda - The Emperor's Prophecy and the Knights-??????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:32.4585  DEBUG  Downloaded track "The Sorcerer's Spooky Altar- ??????????" from url: https://t4.bcbits.com/stream/966059db4c5e9e02eb366f96a1aad24d/mp3-128/2531226707?p=0&ts=1649873835&t=d51f33a05bbbc6a1e177393b45541fa1f41bc3cc&token=1649873835_f59dcc7b662e36615c0b079ccee81d7bd84406e1
2022-04-12 20:17:35.1860  DEBUG  Tags saved for track "05 Risa Takeda - The Sorcerer's Spooky Altar- ??????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:35.2605  DEBUG  Downloaded track "The Enchanted World-???????????" from url: https://t4.bcbits.com/stream/5feb463edb0970d200471ed0fe942438/mp3-128/3438236488?p=0&ts=1649873835&t=5c630e5d798e6913c9aa68141a7cb5df8115e1d5&token=1649873835_c61d7a585cd8c7af273fa2cfe12531ca11a743c0
2022-04-12 20:17:37.2705  DEBUG  Tags saved for track "08 Risa Takeda - The Enchanted World-???????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:37.4625  DEBUG  Cover art saved in tags for track "08 Risa Takeda - The Enchanted World-???????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:37.4795  INFO   Downloaded track "08 Risa Takeda - The Enchanted World-???????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:37.4955  DEBUG  Downloaded track "Torrential Rain in Wasteland-?????" from url: https://t4.bcbits.com/stream/3080c893a37258fcedd68600f08bb8a4/mp3-128/197080604?p=0&ts=1649873835&t=da3fa432e588baf71715ef3c10cce5483c100197&token=1649873835_98460db99ba84869e6a0a97305507ee8415fd9b6
2022-04-12 20:17:40.4505  DEBUG  Tags saved for track "03 Risa Takeda - Torrential Rain in Wasteland-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:40.7490  DEBUG  Cover art saved in tags for track "03 Risa Takeda - Torrential Rain in Wasteland-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:40.7620  INFO   Downloaded track "03 Risa Takeda - Torrential Rain in Wasteland-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:40.7890  DEBUG  Downloaded track "Resurrection of Demons-???????" from url: https://t4.bcbits.com/stream/7ca6b9fc0c36cd09f8c5fe79c708047a/mp3-128/3399568587?p=0&ts=1649873835&t=2d7dd2c5643ecaf993f46ce1dd466ad6bb6881b2&token=1649873835_54fc912234d54173d056bad257fc6d12b29cff02
2022-04-12 20:17:43.7661  DEBUG  Tags saved for track "06 Risa Takeda - Resurrection of Demons-???????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:44.0861  DEBUG  Cover art saved in tags for track "06 Risa Takeda - Resurrection of Demons-???????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:44.1111  INFO   Downloaded track "06 Risa Takeda - Resurrection of Demons-???????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:44.1281  DEBUG  Downloaded track "Clash-?????????" from url: https://t4.bcbits.com/stream/cdd9d59b6bc0ad87e6113dd400996d59/mp3-128/1782693478?p=0&ts=1649873835&t=c0ad4fbc80ce21cef835239c5e705938a8327ed4&token=1649873835_00db8626f2438d7763ea24095a4039469b07a0b5
2022-04-12 20:17:46.2321  DEBUG  Tags saved for track "07 Risa Takeda - Clash-?????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:46.4761  DEBUG  Cover art saved in tags for track "07 Risa Takeda - Clash-?????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:46.4981  INFO   Downloaded track "07 Risa Takeda - Clash-?????????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:46.5161  DEBUG  Downloaded track "Dawn-???" from url: https://t4.bcbits.com/stream/c567150b61c4fcb180f2d778df93733d/mp3-128/436836518?p=0&ts=1649873835&t=9ee3ab7d25e7d7d80a8a0b784882d568a70432ba&token=1649873835_eb6b387df8d5f451b42ac03783c2ab8ff55cb497
2022-04-12 20:17:48.4131  DEBUG  Tags saved for track "10 Risa Takeda - Dawn-???.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:48.6531  DEBUG  Cover art saved in tags for track "10 Risa Takeda - Dawn-???.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:48.6711  INFO   Downloaded track "10 Risa Takeda - Dawn-???.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:48.6891  DEBUG  Downloaded track "Decisive Battle?The Castle Collapses-??????-?????" from url: https://t4.bcbits.com/stream/bc0ca7c0d2f63333cfff6c69dc236e54/mp3-128/2787278508?p=0&ts=1649873835&t=d679c9f33e36acef428b4e1cd4e97d02e9d0e97f&token=1649873835_25a41bebce00ef4505ea15fb7457ce905d52e335
2022-04-12 20:17:51.6171  DEBUG  Tags saved for track "09 Risa Takeda - Decisive Battle?The Castle Collapses-??????-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:51.9241  DEBUG  Cover art saved in tags for track "09 Risa Takeda - Decisive Battle?The Castle Collapses-??????-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:51.9411  INFO   Downloaded track "09 Risa Takeda - Decisive Battle?The Castle Collapses-??????-?????.mp3" from album "?????/The Sorcerer's Castle"
2022-04-12 20:17:51.9721  FATAL  System.IO.IOException The process cannot access the file '\\datengrab\musik_todo\Risa Takeda - ?????_The Sorcerer's Castle [2022]\05 Risa Takeda - The Sorcerer's Spooky Altar- ??????????.mp3' because it is being used by another process.
2022-04-12 20:17:52.0281  FATAL     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at TagLib.File.LocalFileAbstraction.get_WriteStream()
   at TagLib.File.set_Mode(AccessMode value)
   at TagLib.NonContainer.File.Save()
   at BandcampDownloader.DownloadManager.<DownloadAndTagTrackAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.DownloadManager.<>c__DisplayClass14_0.<<DownloadAlbumAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.DownloadManager.<DownloadAlbumAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.DownloadManager.<StartDownloadsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.WindowMain.<StartDownloadAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BandcampDownloader.WindowMain.<ButtonStart_Click>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BandcampDownloader.App.Main()
```

**Comment by Otiel** [comment]
Thanks for the report, will have a look asap.

**Comment by Otiel** [comment]
This should be fixed since v1.5.0
