### ISSUE TITLE
Crash on Windows 11 22623.741

### ISSUE THREAD

**Issue by dertuxmalwieder** [Otiel/BandcampDownloader#232]
Since the last update, BandcampDownloader won't start anymore:

```
2022-10-23 17:58:12.0888  INFO   BandcampDownloader version: 1.4.1
2022-10-23 17:58:12.1390  INFO   .NET Framework version: 4.8 or later
2022-10-23 17:58:17.3268  FATAL  System.NotImplementedException The method or operation is not implemented.
2022-10-23 17:58:17.3268  FATAL     at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BandcampDownloader.App.Main()
```

**Comment by Otiel** [comment]
>Windows 11 22623.741

That's a preview version, right? I guess Microsoft broke the `TaskbarItemInfo`. It looks plausible since they seem to have done work on the taskbar in [this preview](https://blogs.windows.com/windows-insider/2022/10/10/announcing-windows-11-insider-preview-build-22621-741-and-22623-741/).

If you're on preview, do you have a way to report this issue to Microsoft?

**Comment by dertuxmalwieder** [comment]
Yes, it is a preview version. I could report this "issue" to Microsoft, but your tool is the only application that does not behave properly as far as I can see - even Cairo Shell does not display any misbehavior, so I could *guess* that this is not a *bug* in a strict sense.

**Comment by Otiel** [comment]
Do you have any other app that is reporting progress on its taskbar icon?

![image](https://user-images.githubusercontent.com/3851902/197412161-eed378b5-c24e-42c6-ab2d-41791a84126d.png)

If so, is it working correctly?

**Comment by dertuxmalwieder** [comment]
Oh, indeed: No more progress reporting in Vivaldi either! Looks like you are right indeed... sorry.

**Comment by Otiel** [comment]
No worries!

If you wish to report this to Microsoft, send them the following callstack and tell them the bug most probably arises on a `Window` with `TaskbarItemInfo = new TaskbarItemInfo();`

```
System.NotImplementedException The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   ```

**Comment by dertuxmalwieder** [comment]
FYI, the problem was fixed with an update today.

**Comment by Otiel** [comment]
Great news, thanks for the info!
