### ISSUE TITLE
Crashes when doing right-click or into settings - System.InvalidProgramException

### ISSUE THREAD

**Issue by l0ssy** [Otiel/BandcampDownloader#234]
The program crashes as soon as I do a rightclick (such as copy+paste) or go into the settings, or sometimes even when i hover around with the mouse for too long in the program. #It freezes and crashes immediately. 
Been using it for years with no issues. Nothing was changed on my system, the error is reproducable and permanent.

This is the log: 

```
2022-12-07 18:09:15.7566  INFO   BandcampDownloader version: 1.4.1
2022-12-07 18:09:15.8881  INFO   .NET Framework version: 4.8 or later
**2022-12-07 18:09:40.8031  FATAL  System.InvalidProgramException Common Language Runtime detected an invalid program.
2022-12-07 18:09:40.9295  FATAL     at System.Windows.Controls.Primitives.Popup.GetPopupRootLimits(Rect& targetBounds, Rect& screenBounds, Size& limitSize)**
   at System.Windows.Controls.Primitives.Popup.RestrictSize(Size desiredSize)
   at System.Windows.Controls.Primitives.PopupRoot.GetPopupSizeRestrictions(Popup popup, Size desiredSize, Boolean& restrictWidth, Boolean& restrictHeight)
   at System.Windows.Controls.Primitives.PopupRoot.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Controls.Primitives.Popup.SetRootVisualToPopupRoot()
   at System.Windows.Controls.Primitives.Popup.CreateWindow(Boolean asyncCall)
   at System.Windows.Controls.Primitives.Popup.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Data.BindingOperations.SetBinding(DependencyObject target, DependencyProperty dp, BindingBase binding)
   at System.Windows.Controls.Primitives.Popup.CreateRootPopupInternal(Popup popup, UIElement child, Boolean bindTreatMousePlacementAsBottomProperty)
   at System.Windows.Controls.ContextMenu.HookupParentPopup()
   at System.Windows.Controls.ContextMenu.OnIsOpenChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at System.Windows.Documents.TextEditorContextMenu.OnContextMenuOpening(Object sender, ContextMenuEventArgs e)
   at System.Windows.Controls.Primitives.TextBoxBase.OnContextMenuOpening(ContextMenuEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Controls.PopupControlService.RaiseContextMenuOpeningEvent(IInputElement source, Double x, Double y, Boolean userInitiated)
   at System.Windows.Controls.PopupControlService.ProcessMouseUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Controls.PopupControlService.OnPostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at BandcampDownloader.App.Main()
```

What could this mean?

**Comment by Otiel** [comment]
Seems like an environment issue. Try to reinstall .NET Framework v4.8 runtime from https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

**Comment by l0ssy** [comment]
> Seems like an environment issue. Try to reinstall .NET Framework v4.8 runtime from https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

Thanks very much for the help. Unfortunately it still doesn't work. It says .NET Framework is up to date and i even installed the .NET repair tool. Do you have any other idea?

**Comment by Otiel** [comment]
Can you compute the `BandcampDownloader.exe` hash? Either CRC-32, MD5, SHA-1, SHA-256, SHA-512.

If you don't know which program to use, you can either do it with 7-zip or with https://emn178.github.io/online-tools/sha512_file_hash.html, for instance.

**Comment by l0ssy** [comment]
> Can you compute the `BandcampDownloader.exe` hash? Either CRC-32, MD5, SHA-1, SHA-256, SHA-512.
> 
> If you don't know which program to use, you can either do it with 7-zip or with https://emn178.github.io/online-tools/sha512_file_hash.html, for instance.

Thanks again. I don't know much about what you were asking but i used the URL you sent and this is what it gives in respond when i drop the .exe in there:

5f6732356f2c33bfc668ca7ccd5ed54d87f7b05167d9f50dab71e84b135807b18e259618b9d050a4cc046cc521451764fbfa9f798f1ee3def7892008108a756a

**Comment by Otiel** [comment]
Looks good, so I'm a bit out of ideas... ☹️ 

Can you try this build (it's v1.4.1 but rebuilt)?
[BandcampDownloader.zip](https://github.com/Otiel/BandcampDownloader/files/10227254/BandcampDownloader.zip)

**Comment by l0ssy** [comment]
> Looks good, so I'm a bit out of ideas... ☹️
> 
> Can you try this build (it's v1.4.1 but rebuilt)? [BandcampDownloader.zip](https://github.com/Otiel/BandcampDownloader/files/10227254/BandcampDownloader.zip)

Thanks again for your help, this build also crashes with the same pattern. I really don't know what to do anymore, but i am truly convinced that the issue is just my system and i would have to format it. It worked perfectly for years. There's nothing wrong with the program and you have done an awesome job with. Thanks much for your work and support.

**Comment by Otiel** [comment]
Can you try reinstalling .NET Framework 4.7.2 runtime from https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472

**Comment by l0ssy** [comment]
> Can you try reinstalling .NET Framework 4.7.2 runtime from https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472

Otiel, thanks again, that unfortunately also didn't help recently, BUT ! for some random reason the new Windows updates this morning magically fixed the issue! So it indeed must have been something with the updates messing up my system. 
Very happy now, all the best and cheers! :)

**Comment by Otiel** [comment]
Well, a little bit of Windows magic. 😔

Thanks for keeping me in the loop!
