### ISSUE TITLE
Random crashes while trying to download albums (since v0.2.0.0)

### ISSUE THREAD

**Issue by camartinez1229** [Otiel/BandcampDownloader#74]
Sometimes, when I start trying to download one album, the app will crash entirely after downloading around 1-2 MB. It then usually works properly after restarting (very rarely, I have to restart it a second time). Is there any way I can narrow down the reason for the crashes, or would you have an idea? I also don't recall having this issue with 0.1.9.3 or earlier. It started with 0.2.0, and is still present in the current 0.2.4.1. I'm using Windows 8.1 x64, if that helps.

**Comment by Otiel** [comment]
First, could you share the log file (or at least the couple last lines) you've got after the crashes? If it happens every time after the same action, that would help me narrow down the possible issue.

**Comment by camartinez1229** [comment]
```2019-02-02 15:49:00.1810  INFO   Starting download...
2019-02-02 15:49:00.4414  INFO   Retrieving album data for https://zengate.bandcamp.com/releases
2019-02-02 15:49:02.5528  INFO   Computing size for album "Within The Cosmic Void"...
2019-02-02 15:49:05.8336  INFO   Downloaded artwork for album "Within The Cosmic Void"
2019-02-02 15:49:05.8626  DEBUG  Downloading track "Travelling in Deep Crysosleep" from url: https://t4.bcbits.com/stream/de9d4e86331adb6632aeabfca112e6c6/mp3-128/1066328068?p=0&ts=1549226945&t=ddb15e56820d4736f37d95e1f5f754f53dbece9c&token=1549226945_3df9255ae466a53aff8c3a5e5ce1ec744262a0fe
2019-02-02 15:49:05.8626  DEBUG  Downloading track "Sentient Exploration" from url: https://t4.bcbits.com/stream/f0014010c6c6b64a17f53d0f44ac2a5e/mp3-128/1067384055?p=0&ts=1549226945&t=3df02569da2004faeb187fa7a6a7ffb9ef52753f&token=1549226945_f34e09187e5112f3a83463ab41e24601849ad15d
2019-02-02 15:49:05.8626  DEBUG  Downloading track "Ancient Temples of Proxima Centauri B" from url: https://t4.bcbits.com/stream/8c5ecc6fa0ba1ded0914b77d8872a21c/mp3-128/1288733324?p=0&ts=1549226945&t=3cb1c0784865bd91003e6ee019646d1afb120b2b&token=1549226945_24955ea5f8b58a64bc54010e837d6ea5b3c7a7ce
2019-02-02 15:49:05.8626  DEBUG  Downloading track "Frontier" from url: https://t4.bcbits.com/stream/2d942446572381148c344e6a0037ab80/mp3-128/78330186?p=0&ts=1549226945&t=5dcaf5cff4af8befbc7de4e56aea568863a20c57&token=1549226945_ea4e34a4ae91730f7d658eed3d4e48e4fbf9fe2f
2019-02-02 15:49:05.8626  DEBUG  Downloading track "The Cygnus Signal" from url: https://t4.bcbits.com/stream/18a73d5f80137eb12e38dfba4e4453c4/mp3-128/2401286700?p=0&ts=1549226945&t=ec9e0a69bfddf10a52702c8d396e6986c90c550f&token=1549226945_d389c7af28f664c27080cee6dd5772d23e45e25d
2019-02-02 15:49:05.8626  DEBUG  Downloading track "The Center Of Nowhere" from url: https://t4.bcbits.com/stream/619af9b9ea8937dd0cb68469e8bd405a/mp3-128/2428900631?p=0&ts=1549226945&t=257e257f17575aae1f0794e9472cb8d3e74955ab&token=1549226945_6ee96bc23b5e2dc4c13cd471a9674755064d2562
2019-02-02 15:49:21.9202  INFO   Starting download...
2019-02-02 15:49:22.0082  INFO   Retrieving album data for https://zengate.bandcamp.com/releases
2019-02-02 15:49:22.7982  INFO   Computing size for album "Within The Cosmic Void"...
2019-02-02 15:49:23.4042  INFO   Downloaded artwork for album "Within The Cosmic Void"
2019-02-02 15:49:23.4535  DEBUG  Downloading track "The Center Of Nowhere" from url: https://t4.bcbits.com/stream/619af9b9ea8937dd0cb68469e8bd405a/mp3-128/2428900631?p=0&ts=1549226966&t=db1e6a2238a5eb5dc675fe66a3e23da15418a820&token=1549226966_a748df580b7474533181c8e8f3232717b8de93a7
2019-02-02 15:49:23.4535  DEBUG  Downloading track "The Cygnus Signal" from url: https://t4.bcbits.com/stream/18a73d5f80137eb12e38dfba4e4453c4/mp3-128/2401286700?p=0&ts=1549226966&t=dd408ade4c2a8acb982a4896cb642f2b587b6df2&token=1549226966_15a0a2bb85506278b73a71cd054cf4bb2d04d545
2019-02-02 15:49:23.4535  DEBUG  Downloading track "Ancient Temples of Proxima Centauri B" from url: https://t4.bcbits.com/stream/8c5ecc6fa0ba1ded0914b77d8872a21c/mp3-128/1288733324?p=0&ts=1549226966&t=4a8db5d0193552f258b579a2cf265dfd7f4ae1d9&token=1549226966_2dfedfae140bc094be1992707d85b7feadd34146
2019-02-02 15:49:23.4535  DEBUG  Downloading track "Sentient Exploration" from url: https://t4.bcbits.com/stream/f0014010c6c6b64a17f53d0f44ac2a5e/mp3-128/1067384055?p=0&ts=1549226966&t=12af70e53a6507c5437ba9bb0dd3e55c38a957df&token=1549226966_2e5f44af854bde39c2dd156f715c5e45dfa48f72
2019-02-02 15:49:23.4535  DEBUG  Downloading track "Travelling in Deep Crysosleep" from url: https://t4.bcbits.com/stream/de9d4e86331adb6632aeabfca112e6c6/mp3-128/1066328068?p=0&ts=1549226966&t=0d7e0b47f882087b605f148bebaa01acaa098e9b&token=1549226966_d380cd8bf9984bc5e28e531200bd2ec5c9ffcc7a
2019-02-02 15:49:23.4535  DEBUG  Downloading track "Frontier" from url: https://t4.bcbits.com/stream/2d942446572381148c344e6a0037ab80/mp3-128/78330186?p=0&ts=1549226966&t=5afa645254a34e5422b24d165bb769305772c274&token=1549226966_332bfcae41ea5080f51fa071faf6ed787e3d5114
2019-02-02 15:49:25.2788  INFO   Downloaded track "03 Carbon Entity - Frontier.mp3" from album "Within The Cosmic Void"
2019-02-02 15:49:25.2818  INFO   Downloaded track "06 Carbon Entity - The Center Of Nowhere.mp3" from album "Within The Cosmic Void"
2019-02-02 15:49:25.3489  INFO   Downloaded track "05 Carbon Entity - The Cygnus Signal.mp3" from album "Within The Cosmic Void"
2019-02-02 15:49:25.6961  INFO   Downloaded track "02 Carbon Entity - Ancient Temples of Proxima Centauri B.mp3" from album "Within The Cosmic Void"
2019-02-02 15:49:25.8922  INFO   Downloaded track "04 Carbon Entity - Sentient Exploration.mp3" from album "Within The Cosmic Void"
2019-02-02 15:49:25.9803  INFO   Downloaded track "01 Carbon Entity - Travelling in Deep Crysosleep.mp3" from album "Within The Cosmic Void"
2019-02-02 15:49:26.0243  INFO   Successfully downloaded album "Within The Cosmic Void"
```
Okay, above is the log file entries from yesterday, regarding the one album I tried to download. The program crashed after 15:49:05.8626, with no files having been written to my hard drive, apparently. I restarted the program a few seconds later, and it worked properly.

**Comment by Otiel** [comment]
Thanks. Sorry, forgot to ask, mind sharing your settings as well?

If you happen to encounter another crash, please share the new log.

**Comment by camartinez1229** [comment]
Yeah, below are my settings. My DownloadRetry settings are different. A long time before 0.2.0, I adjusted the values to settings I was comfortable with, that had since prevented me from getting blocked by the spam filter, and I put the same values in for 0.2.0+. If it happens to be relevant to my issue, though (I don't know), I'll be happy to restore defaults and see if that helps.
```
DownloadsPath=D:\Music\Bandcamp\
AllowedFileSizeDifference=0.05
DownloadMaxTries=7
DownloadRetryCooldown=1
DownloadRetryExponent=2
SaveCoverArtInFolder=false
CoverArtInFolderConvertToJpg=true
CoverArtInFolderResize=false
CoverArtInFolderMaxSize=1000
SaveCoverArtInTags=true
CoverArtInTagsConvertToJpg=true
CoverArtInTagsResize=true
CoverArtInTagsMaxSize=1000
DownloadOneAlbumAtATime=true
RetrieveFilesSize=false
CheckForUpdates=true
ShowVerboseLog=false
FileNameFormat={tracknum} {artist} - {title}.mp3
ModifyTags=true
TagAlbumArtist=Modify
TagAlbumTitle=Modify
TagArtist=Modify
TagComments=Empty
TagLyrics=Empty
TagTrackNumber=Modify
TagTrackTitle=Modify
TagYear=Modify
Proxy=System
ProxyHttpAddress=
ProxyHttpPort=0
DownloadArtistDiscography=false
```

**Comment by Otiel** [comment]
>A long time before 0.2.0, I adjusted the values to settings I was comfortable with, that had since prevented me from getting blocked by the spam filter, and I put the same values in for 0.2.0+. If it happens to be relevant to my issue, though (I don't know), I'll be happy to restore defaults and see if that helps.

No, that doesn't seem to be linked to the issue here since we can see on your log that the retry mechanism wasn't triggered. Anyway, I've tried to reproduce this bug with your settings, but alas, no luck.

Could you check the following and let me know if you have anything? 
`Event Viewer > Windows Logs > Application > Find > "BandcampDownloader"`

If not, an entry should be added next time you encounter the bug. I'm interested in "Error" entries and any stack trace that could be logged:

![image](https://user-images.githubusercontent.com/3851902/54033201-f234aa80-41b3-11e9-8fe6-348427a58556.png)

**Comment by camartinez1229** [comment]
I checked in my Event Viewer, and following your instructions, I didn't find any logged errors. Well, if you can't figure it out, then it's okay. I only get these crashes rarely, and when I do, it usually works on the 2nd or 3rd try right after. So, not a huge deal.

**Comment by Otiel** [comment]
Ok, thanks for checking this. Next time you encounter this crash, let me know what you see if you get the chance to check the event viewer.

**Comment by NathanJRollins** [comment]
I've been encountering what seems to be the same issue for quite a few updates as well.  Crashes seemingly randomly, downgrading to 0.1.9.3 solves it.  I get the issue consistently, however, so I'm able to retrieve the errors if helpful.  The log says the last thing it was doing a couple seconds before crashing was "Computing size for album" 'XYZ'...

And here's my event viewer error:
`Application: BandcampDownloader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at BandcampDownloader.WindowMain+<>c__DisplayClass22_0.<UpdateProgress>b__0(BandcampDownloader.TrackFile)
   at System.Linq.Enumerable+WhereListIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Enumerable.First[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at BandcampDownloader.WindowMain.UpdateProgress()
   at System.Net.WebClient.OnDownloadProgressChanged(System.Net.DownloadProgressChangedEventArgs)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

**Comment by Otiel** [comment]
👍 Thanks! That'll help me pinpoint the issue.

**Comment by Otiel** [comment]
@NathanJRollins can you share your `BandcampDownloader.ini` content please?

**Comment by NathanJRollins** [comment]
```DownloadsPath=C:\BCDL\{artist}\{album}
AllowedFileSizeDifference=0.05
DownloadMaxTries=7
DownloadRetryCooldown=0.2
DownloadRetryExponent=4
SaveCoverArtInFolder=true
CoverArtFileNameFormat={album}
CoverArtInFolderConvertToJpg=false
CoverArtInFolderResize=false
CoverArtInFolderMaxSize=1500
SaveCoverArtInTags=true
CoverArtInTagsConvertToJpg=true
CoverArtInTagsResize=true
CoverArtInTagsMaxSize=1000
DownloadOneAlbumAtATime=false
RetrieveFilesSize=false
CheckForUpdates=true
EnableApplicationSounds=true
ShowVerboseLog=false
Language=en
Proxy=System
ProxyHttpAddress=
ProxyHttpPort=0
FileNameFormat={tracknum} - {title}.mp3
ModifyTags=true
TagAlbumArtist=Modify
TagAlbumTitle=Modify
TagArtist=Modify
TagComments=DoNotModify
TagLyrics=Modify
TagTrackNumber=Modify
TagTrackTitle=Modify
TagYear=Modify
DownloadArtistDiscography=false
```

**Comment by Otiel** [comment]
Thanks! I believe I've finally found the cause of the crash. This should be fixed in [v0.2.8.0](https://github.com/Otiel/BandcampDownloader/releases/tag/v0.2.8.0). Let me know if you still encounter any issue.

**Comment by camartinez1229** [comment]
Excellent! I had RetrieveFilesSize=false in my settings too, so I'm pretty sure that was the issue in my case too. I'm surprised I never got an error report in the Windows Event Viewer, though. I'd search whenever the app crashed, but never found anything. Oh well. I look forward to using the new version!

**Comment by NathanJRollins** [comment]
Tested & flawless, thank you!
